# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - epub
  - pdf

python:
  version: 3.7
  install:
    - method: pip
      path: .
  system_packages: false
