dist: xenial  # https://docs.travis-ci.com/user/reference/linux
language: python

os: osx
osx_image: xcode12.2  # https://docs.travis-ci.com/user/reference/osx/#macos-version

jobs:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
    - os: linux
      python: 3.9
      env: CLONE_PYTHONNET="false"
    - os: osx
      language: shell
      env: PYTHON=2.7.18
    - os: osx
      language: shell
      env: PYTHON=3.5.10
    - os: osx
      language: shell
      env: PYTHON=3.6.13
    - os: osx
      language: shell
      env: PYTHON=3.7.10
    - os: osx
      language: shell
      env: PYTHON=3.8.9
    - os: osx
      language: shell
      env: PYTHON=3.9.4 CLONE_PYTHONNET="false"

addons:
  apt:
    sources:
      - sourceline: deb https://download.mono-project.com/repo/ubuntu stable-xenial/snapshots/5.20 main
        key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
    packages:
      - mono-devel
      - ca-certificates-mono
      - software-properties-common
      - gcc-multilib
      - g++-multilib
      - gfortran
      - libgfortran3
      - libgfortran3:i386
      - lib32gfortran3
      - libx32gfortran3
      - zlib1g:i386
      - libglib2.0-dev
      - clang

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update
      brew install mono
      brew cask install java
      brew outdated pyenv || brew upgrade pyenv
      pyenv --version
      echo "Available Python versions:"
      pyenv install --list | grep "^\s*\d"
      pyenv install $PYTHON
      export PYENV_VERSION=$PYTHON
      export PATH="/Users/travis/.pyenv/versions/$PYTHON/bin:$PATH"
    fi

install:
  - mono --version
  - java --version
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade setuptools wheel
  - python -m pip install --upgrade pycparser
  - |
    if [ "$CLONE_PYTHONNET" == "true" ]; then
      python -m pip install git+https://github.com/pythonnet/pythonnet.git@c81c3c3db7fcc403d5f4e8298b320240829daab29
    fi
  - python -m pip install --upgrade --editable .[tests]

script:
  - python -m pytest
