# DO NOT EDIT THIS FILE.
#
# The following ensures that this package is included in the 'msl' namespace.
#
import pkgutil
import pkg_resources

__path__ = pkgutil.extend_path(__path__, __name__)

pkg_resources.declare_namespace(__name__)
