# DO NOT EDIT THIS FILE.
#
# The following ensures that this package is included in the 'msl' namespace.
#
# see: https://setuptools.readthedocs.io/en/latest/setuptools.html#namespace-packages
#
__import__('pkg_resources').declare_namespace(__name__)
from . import loadlib
