r"""Check the server's imports.

Run this script using the server32 executable to see which modules from
the standard library cannot be imported.

With the package installed in editable mode, run the following commands
from the root directory of the repository:

   freeze32 --imports msl.examples.loadlib comtypes pythonnet

  .\server32-windows.exe -m .\tests\check_server32_imports.py

The following error will be displayed when the script exits (but that's ok)

  AttributeError: module check_server32_imports.py
  Module does not contain a class that is a subclass of Server32.
  Cannot start the 32-bit server.

"""

import sys
import importlib

# Builtin modules in Python 3 (https://docs.python.org/3/py-modindex.html)
# (module-name, comment)
modules = [
    ("__future__", ""),
    ("__main__", ""),
    ("_thread", ""),
    ("abc", ""),
    ("aifc", "Removed in 3.13"),
    ("argparse", ""),
    ("array", ""),
    ("ast", ""),
    ("asynchat", "Removed in 3.12"),
    ("asyncio", ""),
    ("asyncore", "Removed in 3.12"),
    ("atexit", ""),
    ("audioop", "Removed in 3.13"),
    ("base64", ""),
    ("bdb", ""),
    ("binascii", ""),
    ("bisect", ""),
    ("builtins", ""),
    ("bz2", ""),
    ("calendar", ""),
    ("cgi", "Removed in 3.13"),
    ("cgitb", "Removed in 3.13"),
    ("chunk", "Removed in 3.13"),
    ("cmath", ""),
    ("cmd", ""),
    ("code", ""),
    ("codecs", ""),
    ("codeop", ""),
    ("collections", ""),
    ("collections.abc", ""),
    ("colorsys", ""),
    ("compileall", ""),
    ("concurrent", ""),
    ("concurrent.futures", ""),
    ("configparser", ""),
    ("contextlib", ""),
    ("contextvars", ""),
    ("copy", ""),
    ("copyreg", ""),
    ("cProfile", ""),
    ("crypt", "Unix only; Removed in 3.13"),
    ("csv", ""),
    ("ctypes", ""),
    ("curses", "Unix only"),
    ("curses.ascii", "Unix only"),
    ("curses.panel", "Unix only"),
    ("curses.textpad", "Unix only"),
    ("dataclasses", ""),
    ("datetime", ""),
    ("dbm", ""),
    ("dbm.dumb", ""),
    ("dbm.gnu", "Unix only"),
    ("dbm.ndbm", "Unix only"),
    ("dbm.sqlite3", "Added in 3.13"),
    ("decimal", ""),
    ("difflib", ""),
    ("dis", ""),
    ("distutils", "Removed in 3.12"),
    ("doctest", ""),
    ("email", ""),
    ("email.charset", ""),
    ("email.contentmanager", ""),
    ("email.encoders", ""),
    ("email.errors", ""),
    ("email.generator", ""),
    ("email.header", ""),
    ("email.headerregistry", ""),
    ("email.iterators", ""),
    ("email.message", ""),
    ("email.mime", ""),
    ("email.mime.application", ""),
    ("email.mime.audio", ""),
    ("email.mime.base", ""),
    ("email.mime.image", ""),
    ("email.mime.message", ""),
    ("email.mime.multipart", ""),
    ("email.mime.nonmultipart", ""),
    ("email.mime.text", ""),
    ("email.parser", ""),
    ("email.policy", ""),
    ("email.utils", ""),
    ("encodings", ""),
    ("encodings.idna", ""),
    ("encodings.mbcs", ""),
    ("encodings.utf_8_sig", ""),
    ("ensurepip", "PyInstaller excluded module"),
    ("enum", ""),
    ("errno", ""),
    ("faulthandler", ""),
    ("fcntl", "Unix only"),
    ("filecmp", ""),
    ("fileinput", ""),
    ("fnmatch", ""),
    ("fractions", ""),
    ("ftplib", ""),
    ("functools", ""),
    ("gc", ""),
    ("getopt", ""),
    ("getpass", ""),
    ("gettext", ""),
    ("glob", ""),
    ("graphlib", "Added in 3.9"),
    ("grp", "Unix only"),
    ("gzip", ""),
    ("hashlib", ""),
    ("heapq", ""),
    ("hmac", ""),
    ("html", ""),
    ("html.entities", ""),
    ("html.parser", ""),
    ("http", ""),
    ("http.client", ""),
    ("http.cookiejar", ""),
    ("http.cookies", ""),
    ("http.server", ""),
    ("idlelib", "PyInstaller excluded module"),
    ("imaplib", ""),
    ("imghdr", "Removed in 3.13"),
    ("imp", "Removed in 3.12"),
    ("importlib", ""),
    ("importlib.abc", ""),
    ("importlib.machinery", ""),
    ("importlib.metadata", ""),
    ("importlib.resources", ""),
    ("importlib.resources.abc", "Added in 3.11"),
    ("importlib.util", ""),
    ("inspect", ""),
    ("io", ""),
    ("ipaddress", ""),
    ("itertools", ""),
    ("json", ""),
    ("json.tool", ""),
    ("keyword", ""),
    ("linecache", ""),
    ("locale", ""),
    ("logging", ""),
    ("logging.config", ""),
    ("logging.handlers", ""),
    ("lzma", ""),
    ("mailbox", ""),
    ("mailcap", "Removed in 3.13"),
    ("marshal", ""),
    ("math", ""),
    ("mimetypes", ""),
    ("mmap", ""),
    ("modulefinder", ""),
    ("msilib", "Windows only; Removed in 3.13"),
    ("msvcrt", "Windows only"),
    ("multiprocessing", ""),
    ("multiprocessing.connection", ""),
    ("multiprocessing.dummy", ""),
    ("multiprocessing.managers", ""),
    ("multiprocessing.pool", ""),
    ("multiprocessing.shared_memory", ""),
    ("multiprocessing.sharedctypes", ""),
    ("netrc", ""),
    ("nis", "Unix only; Removed in 3.13"),
    ("nntplib", "Removed in 3.13"),
    ("numbers", ""),
    ("operator", ""),
    ("optparse", ""),
    ("os", ""),
    ("os.path", ""),
    ("ossaudiodev", "Linux and FreeBSD only; Removed in 3.13"),
    ("pathlib", ""),
    ("pdb", ""),
    ("pickle", ""),
    ("pickletools", ""),
    ("pipes", "Unix only; Removed in 3.13"),
    ("pkgutil", ""),
    ("platform", ""),
    ("plistlib", ""),
    ("poplib", ""),
    ("posix", "Unix only"),
    ("pprint", ""),
    ("profile", ""),
    ("pstats", ""),
    ("pty", "Unix only"),
    ("pwd", "Unix only"),
    ("py_compile", ""),
    ("pyclbr", ""),
    ("pydoc", ""),
    ("queue", ""),
    ("quopri", ""),
    ("random", ""),
    ("re", ""),
    ("readline", "Unix only"),
    ("reprlib", ""),
    ("resource", "Unix only"),
    ("rlcompleter", ""),
    ("runpy", ""),
    ("sched", ""),
    ("secrets", ""),
    ("select", ""),
    ("selectors", ""),
    ("shelve", ""),
    ("shlex", ""),
    ("shutil", ""),
    ("signal", ""),
    ("site", ""),
    ("smtpd", "Removed in 3.12"),
    ("smtplib", ""),
    ("sndhdr", "Removed in 3.13"),
    ("socket", ""),
    ("socketserver", ""),
    ("spwd", "Unix only; Removed in 3.13"),
    ("sqlite3", ""),
    ("ssl", ""),
    ("stat", ""),
    ("statistics", ""),
    ("string", ""),
    ("stringprep", ""),
    ("struct", ""),
    ("subprocess", ""),
    ("sunau", "Removed in 3.13"),
    ("symtable", ""),
    ("sys", ""),
    ("sysconfig", ""),
    ("syslog", "Unix only"),
    ("tabnanny", ""),
    ("tarfile", ""),
    ("telnetlib", "Removed in 3.13"),
    ("tempfile", ""),
    ("termios", "Unix only"),
    ("test", "PyInstaller excluded module"),
    ("test.regrtest", "PyInstaller excluded module"),
    ("test.support", "PyInstaller excluded module"),
    ("test.support.bytecode_helper", "PyInstaller excluded module"),
    ("test.support.import_helper", "PyInstaller excluded module"),
    ("test.support.os_helper", "PyInstaller excluded module"),
    ("test.support.script_helper", "PyInstaller excluded module"),
    ("test.support.socket_helper", "PyInstaller excluded module"),
    ("test.support.threading_helper", "PyInstaller excluded module"),
    ("test.support.warnings_helper", "PyInstaller excluded module"),
    ("textwrap", ""),
    ("threading", ""),
    ("time", ""),
    ("timeit", ""),
    ("tkinter", "PyInstaller excluded module"),
    ("tkinter.colorchooser", "PyInstaller excluded module"),
    ("tkinter.commondialog", "PyInstaller excluded module"),
    ("tkinter.dnd", "PyInstaller excluded module"),
    ("tkinter.filedialog", "PyInstaller excluded module"),
    ("tkinter.font", "PyInstaller excluded module"),
    ("tkinter.messagebox", "PyInstaller excluded module"),
    ("tkinter.scrolledtext", "PyInstaller excluded module"),
    ("tkinter.simpledialog", "PyInstaller excluded module"),
    ("tkinter.tix", "PyInstaller excluded module"),
    ("tkinter.ttk", "PyInstaller excluded module"),
    ("token", ""),
    ("tokenize", ""),
    ("tomllib", "Added in 3.11"),
    ("trace", ""),
    ("traceback", ""),
    ("tracemalloc", ""),
    ("tty", "Unix only"),
    ("turtle", "PyInstaller excluded module"),
    ("turtledemo", "PyInstaller excluded module"),
    ("types", ""),
    ("typing", ""),
    ("unicodedata", ""),
    ("unittest", ""),
    ("unittest.mock", ""),
    ("urllib", ""),
    ("urllib.error", ""),
    ("urllib.parse", ""),
    ("urllib.request", ""),
    ("urllib.response", ""),
    ("urllib.robotparser", ""),
    ("uu", "Removed in 3.13"),
    ("uuid", ""),
    ("venv", ""),
    ("warnings", ""),
    ("wave", ""),
    ("weakref", ""),
    ("webbrowser", ""),
    ("winreg", "Windows only"),
    ("winsound", "Windows only"),
    ("wsgiref", ""),
    ("wsgiref.handlers", ""),
    ("wsgiref.headers", ""),
    ("wsgiref.simple_server", ""),
    ("wsgiref.types", "Added in 3.11"),
    ("wsgiref.util", ""),
    ("wsgiref.validate", ""),
    ("xdrlib", "Removed in 3.13"),
    ("xml", ""),
    ("xml.dom", ""),
    ("xml.dom.minidom", ""),
    ("xml.dom.pulldom", ""),
    ("xml.etree.ElementInclude", ""),
    ("xml.etree.ElementTree", ""),
    ("xml.parsers.expat", ""),
    ("xml.parsers.expat.errors", ""),
    ("xml.parsers.expat.model", ""),
    ("xml.sax", ""),
    ("xml.sax.handler", ""),
    ("xml.sax.saxutils", ""),
    ("xml.sax.xmlreader", ""),
    ("xmlrpc", ""),
    ("xmlrpc.client", ""),
    ("xmlrpc.server", ""),
    ("zipapp", ""),
    ("zipfile", ""),
    ("zipimport", ""),
    ("zlib", ""),
    ("zoneinfo", "Added in 3.9"),
]

# these are mandatory
from msl import loadlib
from msl.loadlib import LoadLibrary
from msl.loadlib import Client64
from msl.loadlib import Server32
from msl.loadlib import IS_PYTHON_64BIT
from msl.loadlib import utils
from msl.loadlib import activex
from msl.loadlib.activex import Application
from msl.loadlib.activex import Colour
from msl.examples.loadlib import EXAMPLES_DIR

if sys.version_info[:2] >= (3, 12):
    from sys import monitoring

if sys.platform == "win32":
    import clr
    import comtypes
    import pythonnet

failed = []
for name, comment in modules:
    try:
        importlib.import_module(name)
    except ImportError:
        failed.append((name, comment))

version = ".".join(str(v) for v in sys.version_info[:3])
print(f"These modules cannot be imported by the server running on Python {version}")
length = max(len(name) for name, _ in failed)
for name, comment in failed:
    print(f"  {name:{length}s} {comment}")
print("")
