name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 120

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [windows-2019, ubuntu-20.04, macos-latest]
        architecture: [x64]
        include:
          - python-version: "2.7"
            os: windows-2019
            architecture: x86
          - python-version: "3.5"
            os: windows-2019
            architecture: x86
          - python-version: "3.6"
            os: windows-2019
            architecture: x86
          - python-version: "3.7"
            os: windows-2019
            architecture: x86
          - python-version: "3.8"
            os: windows-2019
            architecture: x86
          - python-version: "3.9"
            os: windows-2019
            architecture: x86
          - python-version: "3.10"
            os: windows-2019
            architecture: x86
          - python-version: "3.11"
            os: windows-2019
            architecture: x86

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install system dependencies (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libgfortran5:i386
      - name: Set up Mono (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        uses: maxim-lobanov/setup-xamarin@v1
        with:
          mono-version: latest
      - name: Mono version (non Windows)
        if: ${{ matrix.os != 'windows-2019' }}
        run: mono --version
      - name: Java version
        run: java -version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install pip, setuptools, wheel and pycparser
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install --upgrade pycparser
      # - name: Install pythonnet from a commit (Python 3.9+)
      #   if: ${{ (matrix.python-version == '3.9' || matrix.python-version == '3.10') }}
      #   run: python -m pip install --upgrade git+https://github.com/pythonnet/pythonnet.git@ac75e0ccc31c2780b57c01fe134652f1f1b90466
      - name: Install msl-loadlib
        run: python -m pip install --upgrade --editable .[tests]
      - name: Uninstall pythonnet (get a fatal crash)
        if: ${{ matrix.os == 'macos-latest' && (matrix.python-version == '2.7' || matrix.python-version == '3.5') }}
        run: python -m pip uninstall --yes pythonnet
      - name: Run tests
        run: python -m pytest
